version: '3.5'

services:
  database:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lojinha
      MYSQL_USER: root
      MYSQL_PASSWORD: root